# Generated by Django 4.1.1 on 2022-10-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
