# Generated by Django 4.1.1 on 2022-10-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
